### ISSUE TITLE
Improve description for OPEN_WEATHER_MAP_LOCATION

### ISSUE THREAD

**Issue by faquin** [ThingPulse/docs#3]
While reading the doc https://docs.thingpulse.com/guides/espaper-plus-kit/ I didn't understand the description for OPEN_WEATHER_MAP_LOCATION
I think it is easier to show an example, like "Paris, FR"

Also, it took me a while to understand the language session. Here again, an example could help, like "fr"

**Comment by marcelstoer** [comment]
You're right, upon reading that paragraph again I have to agree with you. I'll rephrase that.
As a side note, we'll be using the location _id_ rather than its name in future versions by default (in the works: https://github.com/ThingPulse/esp8266-weather-station/pull/122/commits/fdede5ac7651321e32d1e3708dd6c6098ae6b9f5)

However, the comment for the language in `settings.h` should be self-explanatory: https://github.com/ThingPulse/espaper-weatherstation/blob/master/settings.h#L74. How would you change that?

**Comment by faquin** [comment]
For the language, my first try was "French - fr", which obviously didn't work. 
Maybe it's just me :)

I'll add a comment: String OPEN_WEATHER_MAP_LANGUAGE = ""; // language code as listed above
