### ISSUE TITLE
Document WiFi shield firmware update

### ISSUE THREAD

**Issue by ptman** [ThingPulse/docs#5]
Would it be possible to document how to check the version and update the firmware of the WiFi shield in the ESPaper kit, i.e. the ESP8266 Wroom-02?

I'm having some weird trouble with the network and there seem to be newer wifi firmware versions available. I'd like to make sure that isn't the problem. Also, which are the recommended version of the arduino board package? I had trouble with 2.5.0 beta1 (stack dump repeatedly), but 2.4.2 seems to work better. Except HTTP downloads always result in 0 bytes downloaded, even if the Content-Length -header says there's more.

**Comment by marcelstoer** [comment]
> Would it be possible to document how to check the version and update the firmware of the WiFi shield in the ESPaper kit, i.e. the ESP8266 Wroom-02?

Can you explain what you mean by that exactly? The Espressif SDK/firmware is wrapped by the Arduino-core and thus "hidden". You would have to check with the Arduino-core project to figure out which SDK version they use under the hood. Or did you mean how to read the Wroom-02 hardware revision?

> which are the recommended version of the arduino board package? I had trouble with 2.5.0 beta1

I don't think we would ever recommend beta versions 😜In general we recommend using the latest release (currently 2.4.2). AFAIR we only had issues twice with the Arduino-core:
- the semantics of `WiFiClient#connected` recently changed which triggered v1.6.3 and v1.6.4 of our weather station library - and better documentation on their end: https://github.com/esp8266/Arduino/issues/5257
- their 2.3.0 caused WiFi hiccups with certain APs: https://github.com/esp8266/Arduino/issues/4522#issuecomment-381360655

**Comment by ptman** [comment]
> Can you explain what you mean by that exactly?

The ESPaper kit programmed using Arduino is my first contact with the ESP8266. But I found articles on the net complaining that the wifi stack could be old, and could be upgraded to get rid of bugs. And that it was normally not upgraded when uploading your own code.

> The Espressif SDK/firmware is wrapped by the Arduino-core and thus "hidden".

Maybe arduino-core takes care of this. I don't know. How could I verify.

> Or did you mean how to read the Wroom-02 hardware revision?

No. Apparently the wifi firmware version can be read with AT+GMR. How should I do that?

> I don't think we would ever recommend beta versions stuck_out_tongue_winking_eyeIn general we recommend using the latest release (currently 2.4.2).

I didn't mean to imply that you do. But arduino IDE installed the newest 2.5.0-beta1 by default. And it gave me stack traces. Which took a long time to find using the serial monitor. I don't believe it is mentioned either in your guides. Downgrading to 2.4.2 helped with the stack traces, but now I'm left wondering why I get 0 byte downloads.

**Comment by marcelstoer** [comment]
Oh, I see.

I understand by "WiFi stack" or "WiFi firmware" you mean the whole SDK from Espressif (which contains the WiFi stack). The ESP8266 Arduino-core i.e. what the Arduino IDE manages through the platform manager contains that.

I don't know how to find out about the SDK version at runtime. You can take a look at https://github.com/esp8266/Arduino/blob/2.4.2/tools/sdk/version for 2.4.2: some 2.1.0 SDK is used. Looks like the next Arduino-core release will use some 2.2.0 version: https://github.com/esp8266/Arduino/blob/2.5.0-beta2/tools/sdk/version

> And that it was normally not upgraded when uploading your own code.

That happens when you update ESP8266 Arduino-core through the IDE platform manager and then rebuild & upload.

> But arduino IDE installed the newest 2.5.0-beta1 by default.

Interesting...I didn't know it would do that. The IDE usually notifies you about updated libraries or platforms when the become available. As I didn't get a notification about a 2.5.x platform release your statement surprised me. It looks like they do push beta and RC releases via the official channel but just do not "advertise" those via notifications.
<img width="817" alt="screen shot 2018-12-17 at 10 52 55" src="https://user-images.githubusercontent.com/624195/50081322-72b7c080-01ee-11e9-8949-2e29afdfaa56.png">
Our docs now mention that you should currently stick to 2.4.2: https://docs.thingpulse.com/guides/espaper-plus-kit/#install-the-esp8266-toolchain

**Comment by marcelstoer** [comment]
> I don't know how to find out about the SDK version at runtime

Now I do: https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Esp.cpp#L246
